name: "Build and push Docker image"

on:

  push:

    branches:

      - main

      - dev

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v5

      - name: Login to DockerHub

        uses: docker/login-action@v3

        with:

          username: ${{ secrets.seydina88 }}

          password: ${{ secrets.dckr_pat_L7Nh8NczsjMswDqA9dq07lEVNTY }}

      - name: Build and push

        uses: docker/build-push-action@v5

        with:

          push: true

          tags: ${{ secrets.DOCKERHUB_USERNAME }}/application:latest
 